name: pytorch
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - azure-storage-files-datalake-cpp=12.10.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - cryptography=43.0.0
  - datasets=2.20.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - dnspython=2.6.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fastapi=0.111.0
  - fastapi-cli=0.0.4
  - filelock=3.15.4
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.5.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-api-core=2.19.1
  - google-auth=2.33.0
  - google-cloud-core=2.4.1
  - google-cloud-sdk=489.0.0
  - google-cloud-storage=2.18.2
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.63.2
  - grpcio=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.23.4
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.2.1
  - importlib_metadata=7.2.1
  - ipdb=0.13.13
  - ipykernel=6.29.4
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.24
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsentencepiece=0.2.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nltk=3.8.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - orjson=3.10.4
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.7.4
  - pydantic-core=2.18.4
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-multipart=0.0.9
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytorch=2.4.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.5.15
  - requests=2.32.3
  - rich=13.7.1
  - rsa=4.9
  - safetensors=0.4.3
  - scikit-learn=1.3.1
  - scipy=1.13.1
  - sentence-transformers=3.0.1
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=70.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - stack_data=0.6.2
  - starlette=0.37.2
  - sympy=1.12.1
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.19.1
  - toml=0.10.2
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - transformers=4.41.2
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ujson=5.10.0
  - urllib3=2.2.2
  - uvicorn=0.30.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.19.2
  - zstd=1.5.6
  - pip:
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - defusedxml==0.7.1
      - docopt==0.6.2
      - fastjsonschema==2.20.0
      - ipython==8.12.3
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - pandocfilters==1.5.1
      - pipreqs==0.5.0
      - referencing==0.35.1
      - rpds-py==0.20.0
      - soupsieve==2.6
      - tinycss2==1.3.0
      - webencodings==0.5.1
      - yarg==0.1.9